#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Example script that watches a directory for changes and runs the `fnord index`
# command when changes are detected.
#-------------------------------------------------------------------------------

set -eu -o pipefail

DIR=""
PROJECT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -d | --dir)
      DIR="$2"
      shift 2
      ;;

    -p | --project)
      PROJECT="$2"
      shift 2
      ;;

    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [ -z "$DIR" ]; then
  echo "Missing required argument: --dir"
  exit 1
fi

if [ -z "$PROJECT" ]; then
  echo "Missing required argument: --project"
  exit 1
fi

if [ ! -d "$DIR" ]; then
  echo "Directory does not exist: $DIR"
  exit 1
fi

watchman-make \
  -p '**/*' \
  --settle 5 \
  --run "fnord index --quiet --project $PROJECT --dir $DIR"
